### ISSUE TITLE
I CAN STEAL ALL YOUR CODE

### ISSUE THREAD

**Issue by chbachman** [dlillard/MusicProject#1]

**Comment by dlillard** [comment]
Ain't no thang but a chicken wang

**Comment by chbachman** [comment]
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
Leave a comment
